export const MUSIC_PROMPTS = [
  "IndieR&B song for a calm night walk atmosphere, slow tempo around 82 BPM, Intro begins with minimal electric piano notes and subtle city ambience before warm Rhodes chords gradually enter, Soft fingerpicked acoustic guitar appears later in the arrangement, Smooth subtle bass line with extremely minimal brushed snare or nearly absent percussion, Warm acoustic guitar supporting the harmony, relaxed arrangement designed for reading, walking, and background listening, Mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, Vocal melody should stay in a comfortable mid-range with restrained storytelling vocal delivery, Warm natural mix with light reverb, no dramatic build-up, no explosive climax, Target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "IndieFolk song for a calm late-night reflective atmosphere, slow tempo around 72–76 BPM, intro begins with gentle fingerpicked acoustic guitar alone before soft piano textures enter, warm acoustic guitar as the main instrument, subtle piano layers and soft bass support, extremely minimal percussion or nearly absent drums, relaxed arrangement suitable for reading, studying, and background listening, mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, restrained storytelling vocal delivery, warm natural mix with light reverb, reflective nostalgic mood, no dramatic build-up, no explosive climax, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "IndieR&B song with a calm and warm atmosphere suitable for background listening, slow tempo around 76–80 BPM, intro begins with gentle Rhodes chords followed by soft acoustic guitar layers, smooth subtle bass line, extremely minimal brushed snare or nearly absent percussion, relaxed arrangement designed for reading, studying, and walking, mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, restrained emotional delivery, warm natural mix with light reverb, peaceful reflective mood, no dramatic build-up, no explosive climax, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "IndieFolk song for a calm late-night reflective atmosphere, slow tempo around 72–76 BPM, intro begins with gentle piano notes followed by soft fingerpicked acoustic guitar, warm acoustic guitar as the main instrument, subtle piano textures and soft bass support, extremely minimal percussion or nearly absent drums, relaxed arrangement designed for reading, studying, and background listening, mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, restrained storytelling vocal delivery, warm natural mix with light reverb, reflective and peaceful mood, no dramatic build-up, no explosive climax, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Soft indie pop, bright calm mood, 72–76 BPM, acoustic fingerpicking guitar lead, light piano accents, minimal brush drums, soft bass, airy ambient pads, intimate conversational vocal tone, no high notes, gentle reflective atmosphere, smooth flowing arrangement, warm natural mix, soft reverb, gentle fade-out ending, theme: quiet weekend afternoon noticing small changes in everyday life, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Soft indie pop, 76-80 BPM, warm acoustic guitar lead, light felt piano accents, gentle bass, minimal brush drums, airy ambient pads, reflective bus ride atmosphere, intimate soft vocal tone, no high notes, smooth flowing arrangement, warm sunset mood, natural mix, soft reverb, gentle fade-out ending, theme: watching the world through a bus window and quietly feeling a new beginning, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Soft indie folk, 74 BPM, warm acoustic guitar picking, light piano textures, gentle bass, minimal brush drums, calm evening walk atmosphere, reflective male vocal tone, storytelling delivery, no high notes, smooth flowing arrangement, warm natural mix, soft reverb, gentle fade-out ending, theme: pretending nothing changed while quietly realizing something did, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence"
];

export const THEMES = [
  "사랑", "이별", "드라이브", "희망", "여유", "산책", "여행", "밤"
];
